language: python

#Safelist
branches:
  only: 
    - master

jobs:
  include:
    - stage: install
      script: python -m pip install -r requirements.txt
    - stage: test
      script: python -m unittest discover -s tests