
# # coding=utf-8

# from tms.tms_classes import TMSPack, TMSVerse

# TMS_SERIES_1_KEY = "SERIES_1"
# TMS_SERIES_2_KEY = "SERIES_2"
# TMS_SERIES_3_KEY = "SERIES_3"
# TMS_SERIES_4_KEY = "SERIES_4"
# TMS_SERIES_5_KEY = "SERIES_5"

# def keys():
#     return [TMS_SERIES_1_KEY, TMS_SERIES_2_KEY, TMS_SERIES_3_KEY, TMS_SERIES_4_KEY, TMS_SERIES_5_KEY]


# SERIES_1 = [
#     TMSVerse(TMS_SERIES_1_KEY, "", 1, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 2, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 3, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 4, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 5, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 6, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 7, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 8, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 9, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 10, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 11, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 12, "",
#              [])
#     TMSVerse(TMS_SERIES_1_KEY, "", 13, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 14, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 15, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 16, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 17, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 18, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 19, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 20, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 21, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 22, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 23, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 24, "",
#              [])
#     TMSVerse(TMS_SERIES_1_KEY, "", 25, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 26, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 27, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 28, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 29, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 30, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 31, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 32, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 33, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 34, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 35, "",
#              []),
#     TMSVerse(TMS_SERIES_1_KEY, "", 36, "",
#              [])
# ]

# SERIES_2 = [
#     TMSVerse(TMS_SERIES_2_KEY, "", 1, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 2, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 3, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 4, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 5, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 6, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 7, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 8, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 9, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 10, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 11, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 12, "",
#              [])
#     TMSVerse(TMS_SERIES_2_KEY, "", 13, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 14, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 15, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 16, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 17, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 18, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 19, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 20, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 21, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 22, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 23, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 24, "",
#              [])
#     TMSVerse(TMS_SERIES_2_KEY, "", 25, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 26, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 27, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 28, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 29, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 30, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 31, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 32, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 33, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 34, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 35, "",
#              []),
#     TMSVerse(TMS_SERIES_2_KEY, "", 36, "",
#              [])
# ]

# SERIES_3 = [
#     TMSVerse(TMS_SERIES_3_KEY, "", 1, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 2, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 3, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 4, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 5, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 6, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 7, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 8, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 9, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 10, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 11, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 12, "",
#              [])
#     TMSVerse(TMS_SERIES_3_KEY, "", 13, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 14, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 15, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 16, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 17, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 18, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 19, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 20, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 21, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 22, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 23, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 24, "",
#              [])
#     TMSVerse(TMS_SERIES_3_KEY, "", 25, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 26, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 27, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 28, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 29, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 30, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 31, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 32, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 33, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 34, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 35, "",
#              []),
#     TMSVerse(TMS_SERIES_3_KEY, "", 36, "",
#              [])
# ]

# SERIES_4 = [
#     TMSVerse(TMS_SERIES_4_KEY, "", 1, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 2, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 3, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 4, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 5, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 6, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 7, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 8, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 9, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 10, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 11, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 12, "",
#              [])
#     TMSVerse(TMS_SERIES_4_KEY, "", 13, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 14, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 15, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 16, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 17, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 18, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 19, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 20, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 21, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 22, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 23, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 24, "",
#              [])
#     TMSVerse(TMS_SERIES_4_KEY, "", 25, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 26, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 27, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 28, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 29, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 30, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 31, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 32, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 33, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 34, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 35, "",
#              []),
#     TMSVerse(TMS_SERIES_4_KEY, "", 36, "",
#              [])
# ]

# SERIES_5 = [
#     TMSVerse(TMS_SERIES_5_KEY, "", 1, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 2, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 3, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 4, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 5, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 6, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 7, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 8, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 9, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 10, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 11, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 12, "",
#              [])
#     TMSVerse(TMS_SERIES_5_KEY, "", 13, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 14, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 15, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 16, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 17, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 18, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 19, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 20, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 21, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 22, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 23, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 24, "",
#              [])
#     TMSVerse(TMS_SERIES_5_KEY, "", 25, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 26, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 27, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 28, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 29, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 30, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 31, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 32, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 33, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 34, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 35, "",
#              []),
#     TMSVerse(TMS_SERIES_5_KEY, "", 36, "",
#              [])
# ]


# def data():
#     return {
#         TMS_SERIES_1_KEY: A_PACK,
#         TMS_SERIES_2_KEY: B_PACK,
#         TMS_SERIES_3_KEY: C_PACK,
#         TMS_SERIES_4_KEY: D_PACK,
#         TMS_SERIES_5_KEY: E_PACK
#     }


# def names():
#     return {
#         TMS_SERIES_1_KEY: "Series 1: Getting to Know God",
#         TMS_SERIES_2_KEY: "Series 2: Growing in Love",
#         TMS_SERIES_3_KEY: "Series 3: Growing in Faith",
#         TMS_SERIES_4_KEY: "Series 4: Walking in Victory",
#         TMS_SERIES_5_KEY: "Series 5: Sharing Christ with Others"
#     }


# def aliases():
#     return {
#         TMS_SERIES_1_KEY: ["Series 1", "TMS 180 1", "Getting to Know God"],
#         TMS_SERIES_2_KEY: ["Series 2", "TMS 180 2", "Growing in Love"],
#         TMS_SERIES_3_KEY: ["Series 3", "TMS 180 3", "Growing in Faith"],
#         TMS_SERIES_4_KEY: ["Series 4", "TMS 180 4", "Walking in Victory"],
#         TMS_SERIES_5_KEY: ["Series 5", "TMS 180 5", "Sharing Christ with Others"]
#     }


# def top():
#     return TMS_SERIES_1_KEY


# TMS_PACK = TMSPack(keys(), data(), names(), aliases(), top())


# def pack():
#     return TMS_PACK

